const boardEl=document.getElementById('board'),viewport=document.getElementById('viewport'),counterEl=document.getElementById('counter'),modeEl=document.getElementById('mode'),newEl=document.getElementById('new'),zoomEl=document.getElementById('zoom'),statusEl=document.getElementById('status');
const BASE=64,MIN=32,MAX=128;
let w=9,h=9,mines=10,cell=BASE,flagMode=false,lost=false,won=false,minesGenerated=false,flagCount=0,mine=[],open=[],marked=[],number=[],fresh=[];
const colors=['','n1','n2','n3','n4','n5','n6','n7','n8'];
const inside=(x,y)=>x>=0&&x<w&&y>=0&&y<h;
function newGame(W,H,M){w=W;h=H;mines=M;flagCount=0;flagMode=false;lost=won=minesGenerated=false;mine=Array.from({length:h},()=>Array(w).fill(false));open=Array.from({length:h},()=>Array(w).fill(false));marked=Array.from({length:h},()=>Array(w).fill(false));number=Array.from({length:h},()=>Array(w).fill(0));fresh=[];modeEl.textContent='⛏';statusEl.className='status';render();update();}
function generate(sx,sy){let n=0;while(n<mines){const x=Math.floor(Math.random()*w),y=Math.floor(Math.random()*h);if((x===sx&&y===sy)||mine[y][x])continue;mine[y][x]=true;n++;}for(let y=0;y<h;y++)for(let x=0;x<w;x++){let c=0;for(let yy=y-1;yy<=y+1;yy++)for(let xx=x-1;xx<=x+1;xx++)if(inside(xx,yy)&&mine[yy][xx])c++;number[y][x]=c;}minesGenerated=true;}
function reveal(x,y){if(lost||won||!inside(x,y)||open[y][x]||marked[y][x])return;open[y][x]=true;fresh.push([x,y]);if(mine[y][x]){lose();return;}if(number[y][x]===0)for(let yy=y-1;yy<=y+1;yy++)for(let xx=x-1;xx<=x+1;xx++)if(inside(xx,yy)&&(xx!==x||yy!==y))reveal(xx,yy);}
function toggleFlag(x,y){if(open[y][x])return;if(marked[y][x]){marked[y][x]=false;flagCount--;}else if(flagCount<mines){marked[y][x]=true;flagCount++;}}
function chord(x,y,allowFlags){let flags=0,covered=0;for(let yy=y-1;yy<=y+1;yy++)for(let xx=x-1;xx<=x+1;xx++)if(inside(xx,yy)&&!(xx===x&&yy===y)){if(marked[yy][xx])flags++;else if(!open[yy][xx])covered++;}const needed=number[y][x]-flags;if(needed<0)return;if(allowFlags&&needed===covered&&needed>0){for(let yy=y-1;yy<=y+1;yy++)for(let xx=x-1;xx<=x+1;xx++)if(inside(xx,yy)&&!(xx===x&&yy===y)&&!open[yy][xx]&&!marked[yy][xx]){marked[yy][xx]=true;flagCount++;}return;}if(flags!==number[y][x])return;for(let yy=y-1;yy<=y+1;yy++)for(let xx=x-1;xx<=x+1;xx++)if(inside(xx,yy)&&!(xx===x&&yy===y)&&!open[yy][xx]&&!marked[yy][xx]){reveal(xx,yy);if(lost)return;}}
function cascade(){while(fresh.length&&!lost){const [x,y]=fresh.shift();if(open[y][x]&&number[y][x]>0)chord(x,y,false);}}
function lose(){lost=true;for(let y=0;y<h;y++)for(let x=0;x<w;x++)if(mine[y][x])open[y][x]=true;statusEl.textContent='😵';statusEl.className='status show';}
function checkWin(){if(lost)return;for(let y=0;y<h;y++)for(let x=0;x<w;x++)if(!mine[y][x]&&!open[y][x])return;won=true;statusEl.textContent='😎';statusEl.className='status show';}
function clickCell(x,y){if(lost||won)return;if(open[y][x]&&number[y][x]>0)chord(x,y,true);else if(flagMode)toggleFlag(x,y);else{if(!minesGenerated)generate(x,y);reveal(x,y);cascade();}checkWin();render();update();}
function render(){boardEl.style.width=`${w*cell}px`;boardEl.style.height=`${h*cell}px`;boardEl.style.gridTemplateColumns=`repeat(${w},${cell}px)`;boardEl.style.gridTemplateRows=`repeat(${h},${cell}px)`;boardEl.replaceChildren();for(let y=0;y<h;y++)for(let x=0;x<w;x++){const e=document.createElement('div');e.className='cell '+(open[y][x]?'open':'closed');e.style.fontSize=`${cell*.58}px`;if(marked[y][x])e.classList.add('flag');else if(open[y][x]&&mine[y][x])e.classList.add('mine');else if(open[y][x]&&number[y][x]){e.textContent=number[y][x];e.classList.add(colors[number[y][x]]);}e.dataset.x=x;e.dataset.y=y;boardEl.appendChild(e);}}
function update(){counterEl.textContent='💣 '+Math.max(0,mines-flagCount);zoomEl.textContent=Math.round(cell/BASE*100)+'%';newEl.textContent=lost?'😵':won?'😎':'🙂';}
boardEl.addEventListener('click',e=>{const c=e.target.closest('.cell');if(c)clickCell(+c.dataset.x,+c.dataset.y);});
modeEl.onclick=()=>{flagMode=!flagMode;modeEl.textContent=flagMode?'⚑':'⛏';};newEl.onclick=()=>newGame(w,h,mines);document.querySelectorAll('[data-size]').forEach(b=>b.onclick=()=>newGame(...b.dataset.size.split(',').map(Number)));
let pinchStart=null,startCell=cell;
viewport.addEventListener('touchstart',e=>{if(e.touches.length===2){pinchStart=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);startCell=cell;}},{passive:true});
viewport.addEventListener('touchmove',e=>{if(e.touches.length!==2||pinchStart===null)return;e.preventDefault();const d=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);cell=Math.max(MIN,Math.min(MAX,Math.round(startCell*d/pinchStart)));render();update();},{passive:false});viewport.addEventListener('touchend',()=>pinchStart=null,{passive:true});
window.addEventListener('wheel',e=>{if(e.ctrlKey){e.preventDefault();cell=Math.max(MIN,Math.min(MAX,Math.round(cell*(e.deltaY<0?1.1:.9))));render();update();}},{passive:false});
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');newGame(9,9,10);